### ISSUE TITLE
Running the unittest produces warnings and closing errors.

### ISSUE THREAD

**Issue by CumulonimbusCalvus** [QuTech-Delft/qtt#454]
@peendebak If times allows, I will have a look... Just posting it here as a reminder :notebook:.

**What I did?:**
Checked out the master branch. Installed using pip and ran the unittests with pytest.

**What should have happend?:**
All unittests should have been executed without warnings.

**What happend?:**
See the following output.

```
(spinqubits) D:\***>pytest
============================= test session starts =============================
platform win32 -- Python 3.6.5, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: D:\***\qtt, inifile: pytest.ini
collected 63 items

qtt\data.py .........                                                    [ 14%]
blablabla...
qtt\utilities\tools.py .....                                             [100%]
============================== warnings summary ===============================
qtt/measurements/storage.py::test_load_save_state
  C:\Users\tud278322\AppData\Local\conda\conda\envs\lcblom\lib\site-packages\hic
kle\hickle.py:409: SerializedWarning: <class 'collections.OrderedDict'> type not
 understood, data have been serialized
    warnings.warn("%s type not understood, data have been serialized" % type(py_
obj), SerializedWarning)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=================== 63 passed, 1 warnings in 17.28 seconds ====================
Failed to close virt_gates, ignored
Traceback (most recent call last):
  File "d:\users\lcblom\git\qcodes\qcodes\instrument\base.py", line 511, in clos
e_all
    inst = cls.find_instrument(inststr)
  File "d:\users\lcblom\git\qcodes\qcodes\instrument\base.py", line 608, in find
_instrument
    raise KeyError('Instrument {} has been removed'.format(name))
KeyError: 'Instrument virt_gates has been removed'
Failed to close testivvi, ignored
Traceback (most recent call last):
  File "d:\users\lcblom\git\qcodes\qcodes\instrument\base.py", line 511, in clos
e_all
    inst = cls.find_instrument(inststr)
  File "d:\users\lcblom\git\qcodes\qcodes\instrument\base.py", line 608, in find
_instrument
    raise KeyError('Instrument {} has been removed'.format(name))
KeyError: 'Instrument testivvi has been removed'
Failed to close testvgates, ignored
Traceback (most recent call last):
  File "d:\users\lcblom\git\qcodes\qcodes\instrument\base.py", line 511, in clos
e_all
    inst = cls.find_instrument(inststr)
  File "d:\users\lcblom\git\qcodes\qcodes\instrument\base.py", line 608, in find
_instrument
    raise KeyError('Instrument {} has been removed'.format(name))
KeyError: 'Instrument testvgates has been removed'
```

**Comment by CumulonimbusCalvus** [comment]
Partly solved by #507.
